sudo: true
dist: trusty
language: python
python:
- '3.4'
- '3.5'
env:
- TOX_ENV=tan1uan5
- TOX_ENV=flake8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - automake
    - libtool
    - libav-tools  
    - libmp3lame0
    - libass5
install:
- sudo apt-get install -y libavcodec-extra-54 libx11-dev libx11-dev:i386
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls
