# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='圖片表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('使用者類型', models.CharField(max_length=200)),
                ('使用者編號', models.IntegerField()),
                ('檔案', models.FileField(upload_to='')),
            ],
        ),
    ]
