# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line回應', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='圖片表',
            name='使用者編號',
            field=models.CharField(max_length=200),
        ),
    ]
