# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line回應', '0002_auto_20170510_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='結果影片表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('檔案', models.FileField(upload_to='')),
            ],
        ),
    ]
